# Generated by Django 4.1.4 on 2022-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_catego", models.CharField(default="", max_length=70)),
                ("name", models.CharField(default="", max_length=200)),
                ("products", models.CharField(default="", max_length=200)),
                ("url", models.CharField(default="", max_length=200)),
                ("SameAs", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
                ("mail", models.CharField(default="", max_length=200)),
                ("password", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
