# Generated by Django 4.1.4 on 2022-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="", max_length=70)),
                ("keywords", models.CharField(default="", max_length=200)),
                ("categories_tags", models.CharField(default="", max_length=200)),
                ("countries", models.CharField(default="", max_length=200)),
                ("image_url", models.CharField(default="", max_length=200)),
                ("ingredients_text", models.CharField(default="", max_length=200)),
                ("user_id", models.CharField(default="", max_length=200)),
                ("historique", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
